/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quizgame;

/**
 *
 * @author RichardBadea
 */

import javax.swing.JOptionPane;

public class GuessingGameGUI extends javax.swing.JFrame {
    //declare variables
     //declare variables 
    String[] questions;
    String[] correctAnswers;
    String answer;
    
    int index;
    int score = 0;
    
 

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GuessingGameGUI.class.getName());

    /**
     * Creates new form GuessingGameGUI
     */
    public GuessingGameGUI() {
        initComponents();
       
        answer = new String();
        
        questions = new String[5];
        questions[0] = "What percentage(%) of total employment is made up by the middle class?";
        questions[1] = "How many people were unemployed in 2015?";
        questions[2] = "How many workers have lived in extreme or moderate poverty in 2018?";
        questions[3] = "How many targets does the UN wish to achieve by 2030? (for this SDG)";
        questions[4] = "What is the minimun annual growth needed to be achieved?";
        
        correctAnswers = new String[5];
        correctAnswers[0] = "34%";
        correctAnswers[1] = "More than 204 million";
        correctAnswers[2] = "Some 700 million";
        correctAnswers[3] = "12";
        correctAnswers[4] = "7";
        
        index = 0;
        
        questionLbl.setText(questions[index]);
        score = 0;
    

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        answerBtn = new javax.swing.JButton();
        answerTf = new javax.swing.JTextField();
        questionLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(255, 0, 0));
        titleLbl.setText("Quiz Game Application");

        answerBtn.setBackground(new java.awt.Color(51, 255, 51));
        answerBtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        answerBtn.setText("Ok");
        answerBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        answerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerBtnActionPerformed(evt);
            }
        });

        answerTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerTfActionPerformed(evt);
            }
        });

        questionLbl.setText("Sample question text");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(answerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(questionLbl)
                            .addComponent(answerTf, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(titleLbl)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(titleLbl)
                .addGap(18, 18, 18)
                .addComponent(questionLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(answerTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(answerBtn)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void answerTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerTfActionPerformed

    private void answerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerBtnActionPerformed
        // TODO add your handling code here:
        answer = answerTf.getText();

    if (answer.equalsIgnoreCase(correctAnswers[index])) {
        score++;
    }

    index++;  // move to next question

    if (index < questions.length) {
        // Show next question
        questionLbl.setText(questions[index]);
        answerTf.setText("");  // clear input
    } 
    else {
        // No more questions — show final score
        JOptionPane.showMessageDialog(this,
            """
            Game Over.
            Your score: """ + score + "/" + questions.length);
    }

    }//GEN-LAST:event_answerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GuessingGameGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton answerBtn;
    private javax.swing.JTextField answerTf;
    private javax.swing.JLabel questionLbl;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
